variables:
  GIT_SUBMODULE_STRATEGY: recursive


# Natively build and test the project
job-native-build:
  script:
    - sudo .ci_scripts/test-build/install_packages.sh
    - ./build.sh
    - .ci_scripts/test-build/run_tests.sh
    - .ci_scripts/test-build/run_tests.sh valgrind
    - .ci_scripts/test-build/run_cppcheck.sh
    - .ci_scripts/test-build/add_nft_rules.sh
    #- .ci_scripts/test-build/run_exec.sh


# Cross-compile the project for the TL-WDR4900 router
job-cross-compilation:
  script:
    - docker compose run --rm --remove-orphans cross-compilation /home/user/iot-firewall/docker_cmd.sh tl-wdr4900 $(id -u $(whoami)) $(id -g $(whoami))
