name: full-test
on: [push]


jobs:

  native-build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required packages
        run: sudo $GITHUB_WORKSPACE/.ci_scripts/native-build/install_packages.sh

      - name: Build project with CMake
        run: $GITHUB_WORKSPACE/build.sh -d $GITHUB_WORKSPACE

      - name: Run CUnit tests
        run: $GITHUB_WORKSPACE/.ci_scripts/native-build/run_tests.sh

      - name: Run Valgrind on CUnit tests
        run: $GITHUB_WORKSPACE/.ci_scripts/native-build/run_tests.sh valgrind

      - name: Run cppcheck on source files
        run: $GITHUB_WORKSPACE/.ci_scripts/native-build/run_cppcheck.sh
      
      - name: Add NFTables rules
        run:  $GITHUB_WORKSPACE/.ci_scripts/native-build/add_nft_rules.sh

      - name: Run NFQueue executables
        run: $GITHUB_WORKSPACE/.ci_scripts/native-build/run_exec.sh


  cross-compile:
    runs-on: ubuntu-latest
    container: fdekeers/openwrt_tl-wdr4900_gha

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run cross-compilation
        run: $GITHUB_WORKSPACE/build.sh -d $GITHUB_WORKSPACE -t $GITHUB_WORKSPACE/openwrt/tl-wdr4900.cmake
